"""Program discovery: which programs CoursePilot can evaluate (Phase 6.0).

```
School ─< Program ─< ProgramVersion (one per catalog year) ─< Requirement tree
```

A client choosing or comparing majors needs three answers the frontend must
never invent: what exists, for which catalog years, and whether CoursePilot
can evaluate it honestly. This module derives all three from the database -
it holds no program list of its own, and nothing here names a program.

## Identifiers

A program is addressed by a **natural key**, `sas-640-ba`: school code,
program code and degree type - exactly `uq_program_natural_key`. A version
is that key plus a catalog year. Internal UUIDs are never exposed:

  * they are surrogate keys, regenerated by a re-ingest, so a mobile client
    that stored one would silently point at nothing after a reload;
  * the natural key is what Rutgers itself publishes ("Mathematics 640, B.A.,
    2026-2027"), so it is stable across databases and meaningful to a human.

Degree type is part of the key because the Rutgers CS page defines a B.A. and
a B.S. with different requirements: two programs, not one with a flag.

## Support status

Derived from curation provenance, never asserted:

| status | meaning |
|---|---|
| `supported` | every requirement and rule was curated from official prose by a person |
| `pending_review` | requirements exist, but some are `unverified` - e.g. encoded by a model and not yet checked by a person. Evaluable, and every result says so |
| `unavailable` | no requirements, or test-only `synthetic` data. Never evaluated |

A program is never reported more trustworthy than its least-verified node.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from decimal import Decimal
from enum import StrEnum

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.models import (
    CurationStatus,
    Program,
    ProgramRule,
    ProgramVersion,
    Requirement,
    School,
)


class SupportStatus(StrEnum):
    SUPPORTED = "supported"
    PENDING_REVIEW = "pending_review"
    UNAVAILABLE = "unavailable"

    @property
    def evaluable(self) -> bool:
        return self is not SupportStatus.UNAVAILABLE


_KEY_PART = re.compile(r"^[a-z0-9]+$")


class InvalidProgramKey(ValueError):
    """The key is not of the form `<school>-<program>-<degree>`."""


def program_key(school_code: str, program_code: str, degree_type: str) -> str:
    """`SAS`, `640`, `BA` -> `sas-640-ba`."""
    return "-".join(part.lower() for part in (school_code, program_code, degree_type))


def parse_program_key(key: str) -> tuple[str, str, str]:
    """`sas-640-ba` -> (`sas`, `640`, `ba`), lower-cased.

    Strict: exactly three alphanumeric parts. Matching against the database
    is case-insensitive, so the key never depends on how a code was cased.
    """
    parts = key.split("-")
    if len(parts) != 3 or not all(_KEY_PART.match(p) for p in parts):
        raise InvalidProgramKey(f"not a program key: {key!r}")
    return parts[0], parts[1], parts[2]


@dataclass(frozen=True, slots=True)
class ProgramVersionInfo:
    catalog_year: str
    support_status: SupportStatus
    curation_status: str
    requirement_count: int
    rule_count: int
    not_evaluable_rule_count: int
    total_credits_min: Decimal | None
    total_credits_max: Decimal | None
    sharing_policy: str
    source_url: str | None


@dataclass(frozen=True, slots=True)
class ProgramInfo:
    program_key: str
    school_code: str
    school_name: str
    program_code: str
    name: str
    degree_type: str
    versions: tuple[ProgramVersionInfo, ...]


def support_status(
    version_curation: str, node_curations: list[str], requirement_count: int
) -> SupportStatus:
    """The least-verified node decides. See the module docstring."""
    statuses = {version_curation, *node_curations}
    if requirement_count == 0 or CurationStatus.SYNTHETIC.value in statuses:
        return SupportStatus.UNAVAILABLE
    if statuses == {CurationStatus.CURATED_FROM_PROSE.value}:
        return SupportStatus.SUPPORTED
    return SupportStatus.PENDING_REVIEW


def _version_info(session: Session, version: ProgramVersion) -> ProgramVersionInfo:
    requirement_curations = list(
        session.scalars(
            select(Requirement.curation_status).where(
                Requirement.program_version_id == version.id
            )
        ).all()
    )
    rules = list(
        session.execute(
            select(ProgramRule.curation_status, ProgramRule.is_evaluable).where(
                ProgramRule.program_version_id == version.id
            )
        ).all()
    )
    return ProgramVersionInfo(
        catalog_year=version.catalog_year,
        support_status=support_status(
            version.curation_status,
            requirement_curations + [c for c, _ in rules],
            len(requirement_curations),
        ),
        curation_status=version.curation_status,
        requirement_count=len(requirement_curations),
        rule_count=len(rules),
        not_evaluable_rule_count=sum(1 for _, evaluable in rules if not evaluable),
        total_credits_min=version.total_credits_min,
        total_credits_max=version.total_credits_max,
        sharing_policy=version.sharing_policy,
        source_url=version.source_url,
    )


def _program_info(session: Session, program: Program, school: School) -> ProgramInfo:
    versions = sorted(program.versions, key=lambda v: v.catalog_year, reverse=True)
    return ProgramInfo(
        program_key=program_key(school.code, program.code, program.degree_type),
        school_code=school.code,
        school_name=school.name,
        program_code=program.code,
        name=program.name,
        degree_type=program.degree_type,
        versions=tuple(_version_info(session, v) for v in versions),
    )


def list_programs(session: Session) -> list[ProgramInfo]:
    """Every program with at least one version, ordered by school then name.

    Programs whose every version is `unavailable` are still listed - hiding
    them would make "not yet curated" indistinguishable from "does not exist".
    """
    rows = session.execute(
        select(Program, School)
        .join(School, School.id == Program.school_id)
        .where(select(func.count(ProgramVersion.id))
               .where(ProgramVersion.program_id == Program.id)
               .scalar_subquery() > 0)
        .order_by(School.code, Program.name, Program.degree_type)
    ).all()
    return [_program_info(session, program, school) for program, school in rows]


def find_program(session: Session, key: str) -> tuple[Program, School] | None:
    school_code, code, degree_type = parse_program_key(key)
    row = session.execute(
        select(Program, School)
        .join(School, School.id == Program.school_id)
        .where(
            func.lower(School.code) == school_code,
            func.lower(Program.code) == code,
            func.lower(Program.degree_type) == degree_type,
        )
    ).first()
    return None if row is None else (row[0], row[1])


def get_program(session: Session, key: str) -> ProgramInfo | None:
    found = find_program(session, key)
    return None if found is None else _program_info(session, *found)


def version_info(session: Session, version: ProgramVersion) -> ProgramVersionInfo:
    return _version_info(session, version)


__all__ = [
    "InvalidProgramKey",
    "ProgramInfo",
    "ProgramVersionInfo",
    "SupportStatus",
    "find_program",
    "get_program",
    "list_programs",
    "parse_program_key",
    "program_key",
    "support_status",
    "version_info",
]
