"""Program discovery: which programs CoursePilot can evaluate (Phase 6.0).

```
School ─< Program ─< ProgramVersion (one per catalog year) ─< Requirement tree
```

A client choosing or comparing majors needs three answers the frontend must
never invent: what exists, for which catalog years, and whether CoursePilot
can evaluate it honestly. This module derives all three from the database -
it holds no program list of its own, and nothing here names a program.

## Identifiers

A program is addressed by a **natural key**, `sas-198-ba`: school code,
program code, degree type and - when the program has variants - the variant
slug, `sas-640-ba-option-a`: exactly `uq_program_natural_key`. A version
is that key plus a catalog year. Internal UUIDs are never exposed:

  * they are surrogate keys, regenerated by a re-ingest, so a mobile client
    that stored one would silently point at nothing after a reload;
  * the natural key is what Rutgers itself publishes ("Mathematics 640, B.A.,
    2026-2027"), so it is stable across databases and meaningful to a human.

Degree type is part of the key because the Rutgers CS page defines a B.A. and
a B.S. with different requirements: two programs, not one with a flag.

## Support status

Derived from the version's lifecycle (Phase 6.3, app.services.program_lifecycle),
never asserted:

| status | meaning |
|---|---|
| `supported` | lifecycle `published`: approved by a named human against the current source, or grandfathered (`publication_basis = legacy_curated`) |
| `pending_review` | requirements exist but the version is parsed, validated, reviewed-not-published or `needs_rereview`. Evaluable, and every result says so |
| `unavailable` | no requirements, or test-only `synthetic` data. Never evaluated |

Before Phase 6.3 "supported" meant "every node is labelled curated_from_prose"
- a label anyone editing a JSON file could write. Publication now takes a
recorded review, so the label alone can no longer make a program supported.

## Discovered programs

Catalog pages and credential candidates found by the discovery registry are
listed separately (`list_discovered`) and only on request. They are claims
about the catalog, not programs: they have no requirements, cannot be
audited, and never appear in the student-facing program list.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import StrEnum

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.models import (
    CatalogPage,
    CurationStatus,
    Program,
    ProgramCandidate,
    ProgramRule,
    ProgramVersion,
    Requirement,
    School,
)


class SupportStatus(StrEnum):
    SUPPORTED = "supported"
    PENDING_REVIEW = "pending_review"
    UNAVAILABLE = "unavailable"

    @property
    def evaluable(self) -> bool:
        return self is not SupportStatus.UNAVAILABLE


_KEY_PART = re.compile(r"^[a-z0-9]+$")


class InvalidProgramKey(ValueError):
    """The key is not of the form `<school>-<program>-<degree>[-<variant>]`."""


class ProgramVariantRequired(LookupError):
    """The key names a program that exists ONLY as variants (Phase 6.4).

    `sas-640-ba` when Rutgers defines Mathematics Options A, B and C: the
    options have different requirements, so evaluating "Mathematics" would
    mean choosing one. CoursePilot never chooses; it returns the choices.
    """

    def __init__(self, key: str, variants: list[str]) -> None:
        super().__init__(f"{key!r} has variants; choose one of: {', '.join(variants)}")
        self.key = key
        self.variants = variants


def program_key(school_code: str, program_code: str, degree_type: str,
                variant: str = "") -> str:
    """`SAS`, `640`, `BA`, `option-a` -> `sas-640-ba-option-a`."""
    parts = [school_code, program_code, degree_type] + ([variant] if variant else [])
    return "-".join(part.lower() for part in parts)


def parse_program_key(key: str) -> tuple[str, str, str, str]:
    """`sas-640-ba-option-a` -> (`sas`, `640`, `ba`, `option-a`), lower-cased.

    Strict: at least three alphanumeric parts; everything after the third is
    the variant slug ('' when absent). Matching against the database is
    case-insensitive, so the key never depends on how a code was cased.
    """
    parts = key.split("-")
    if len(parts) < 3 or not all(_KEY_PART.match(p) for p in parts):
        raise InvalidProgramKey(f"not a program key: {key!r}")
    return parts[0], parts[1], parts[2], "-".join(parts[3:])


@dataclass(frozen=True, slots=True)
class ProgramVersionInfo:
    catalog_year: str
    support_status: SupportStatus
    lifecycle_state: str
    publication_basis: str | None
    curation_status: str
    requirement_count: int
    rule_count: int
    not_evaluable_rule_count: int
    total_credits_min: Decimal | None
    total_credits_max: Decimal | None
    sharing_policy: str
    source_url: str | None
    curated_by: str | None
    source_prose_sha256: str | None
    last_checked_at: datetime | None


@dataclass(frozen=True, slots=True)
class ProgramInfo:
    program_key: str
    school_code: str
    school_name: str
    program_code: str
    name: str
    degree_type: str
    variant: str
    versions: tuple[ProgramVersionInfo, ...]


@dataclass(frozen=True, slots=True)
class DiscoveredEntry:
    """A catalog page, or one credential candidate on a fetched page."""

    catalog_year: str
    school_slug: str
    page_title: str
    url_path: str
    source_page_id: str | None
    lifecycle: str                     # discovered | parsed
    candidate_key: str | None
    heading: str | None
    credential_type: str | None


def support_status(lifecycle_state: str, node_curations: list[str],
                   requirement_count: int) -> SupportStatus:
    """Published is supported; anything else with requirements is pending."""
    if requirement_count == 0 or CurationStatus.SYNTHETIC.value in node_curations:
        return SupportStatus.UNAVAILABLE
    if lifecycle_state == "published":
        return SupportStatus.SUPPORTED
    return SupportStatus.PENDING_REVIEW


def _node_facts(session: Session, version_ids: list) -> tuple[dict, dict]:
    """Requirement curations and rules for many versions in two queries."""
    reqs: dict = {vid: [] for vid in version_ids}
    rules: dict = {vid: [] for vid in version_ids}
    if not version_ids:
        return reqs, rules
    for vid, curation in session.execute(
            select(Requirement.program_version_id, Requirement.curation_status)
            .where(Requirement.program_version_id.in_(version_ids))):
        reqs[vid].append(curation)
    for vid, curation, evaluable in session.execute(
            select(ProgramRule.program_version_id, ProgramRule.curation_status,
                   ProgramRule.is_evaluable)
            .where(ProgramRule.program_version_id.in_(version_ids))):
        rules[vid].append((curation, evaluable))
    return reqs, rules


def _build_version_info(version: ProgramVersion, req_curations: list,
                        rules: list) -> ProgramVersionInfo:
    return ProgramVersionInfo(
        catalog_year=version.catalog_year,
        support_status=support_status(
            version.lifecycle_state,
            [version.curation_status, *req_curations, *(c for c, _ in rules)],
            len(req_curations)),
        lifecycle_state=version.lifecycle_state,
        publication_basis=version.publication_basis,
        curation_status=version.curation_status,
        requirement_count=len(req_curations),
        rule_count=len(rules),
        not_evaluable_rule_count=sum(1 for _, evaluable in rules if not evaluable),
        total_credits_min=version.total_credits_min,
        total_credits_max=version.total_credits_max,
        sharing_policy=version.sharing_policy,
        source_url=version.source_url,
        curated_by=version.curated_by,
        source_prose_sha256=version.source_prose_sha256,
        last_checked_at=version.last_checked_at,
    )


def _version_info(session: Session, version: ProgramVersion) -> ProgramVersionInfo:
    reqs, rules = _node_facts(session, [version.id])
    return _build_version_info(version, reqs[version.id], rules[version.id])


def _programs_info(session: Session, rows: list[tuple[Program, School]]) -> list[ProgramInfo]:
    """Assemble many programs with a fixed number of queries (no N+1)."""
    program_ids = [program.id for program, _ in rows]
    versions_by_program: dict = {pid: [] for pid in program_ids}
    if program_ids:
        for version in session.scalars(
                select(ProgramVersion).where(ProgramVersion.program_id.in_(program_ids))):
            versions_by_program[version.program_id].append(version)
    all_versions = [v for vs in versions_by_program.values() for v in vs]
    reqs, rules = _node_facts(session, [v.id for v in all_versions])
    out = []
    for program, school in rows:
        versions = sorted(versions_by_program[program.id], key=lambda v: v.catalog_year,
                          reverse=True)
        out.append(ProgramInfo(
            program_key=program_key(school.code, program.code, program.degree_type,
                                    program.variant),
            school_code=school.code,
            school_name=school.name,
            program_code=program.code,
            name=program.name,
            degree_type=program.degree_type,
            variant=program.variant,
            versions=tuple(_build_version_info(v, reqs[v.id], rules[v.id]) for v in versions),
        ))
    return out


def list_programs(session: Session) -> list[ProgramInfo]:
    """Every program with at least one version, ordered by school then name.

    Programs whose every version is `unavailable` are still listed - hiding
    them would make "not yet curated" indistinguishable from "does not exist".
    Discovered-only catalog entries are NOT programs and are never listed
    here; see `list_discovered`.
    """
    rows = session.execute(
        select(Program, School)
        .join(School, School.id == Program.school_id)
        .where(select(func.count(ProgramVersion.id))
               .where(ProgramVersion.program_id == Program.id)
               .scalar_subquery() > 0)
        .order_by(School.code, Program.name, Program.degree_type, Program.variant)
    ).all()
    return _programs_info(session, [(p, s) for p, s in rows])


def list_discovered(session: Session, catalog_year: str | None = None) -> list[DiscoveredEntry]:
    """Catalog entries with no curated program version behind them.

    A fetched page contributes one entry per credential candidate that is not
    linked to a version (lifecycle `parsed`); an unfetched program page
    contributes itself (lifecycle `discovered`). Pages classified `other` or
    `external` (policies, faculty lists) are not program sources and are left
    out. Two queries regardless of size.
    """
    pages_q = select(CatalogPage).where(
        CatalogPage.page_class.in_(("subject_coded", "program_area")))
    if catalog_year:
        pages_q = pages_q.where(CatalogPage.catalog_year == catalog_year)
    pages = list(session.scalars(pages_q.order_by(
        CatalogPage.catalog_year, CatalogPage.school_slug, CatalogPage.title)))
    cands: dict = {p.id: [] for p in pages}
    if pages:
        for c in session.scalars(select(ProgramCandidate)
                                 .where(ProgramCandidate.catalog_page_id.in_(list(cands)))
                                 .order_by(ProgramCandidate.candidate_key)):
            cands[c.catalog_page_id].append(c)
    out: list[DiscoveredEntry] = []
    for page in pages:
        base = dict(catalog_year=page.catalog_year, school_slug=page.school_slug,
                    page_title=page.title, url_path=page.url_path,
                    source_page_id=page.source_page_id)
        if page.snapshot_id is None:
            out.append(DiscoveredEntry(**base, lifecycle="discovered", candidate_key=None,
                                       heading=None, credential_type=None))
            continue
        for c in cands[page.id]:
            if c.program_version_id is None:
                out.append(DiscoveredEntry(**base, lifecycle="parsed",
                                           candidate_key=c.candidate_key, heading=c.heading,
                                           credential_type=c.credential_type))
    return out


def find_program(session: Session, key: str) -> tuple[Program, School] | None:
    """Exact natural-key lookup. A variant-less key that matches only
    variants raises ProgramVariantRequired rather than picking one."""
    school_code, code, degree_type, variant = parse_program_key(key)
    rows = session.execute(
        select(Program, School)
        .join(School, School.id == Program.school_id)
        .where(
            func.lower(School.code) == school_code,
            func.lower(Program.code) == code,
            func.lower(Program.degree_type) == degree_type,
        )
        .order_by(Program.variant)
    ).all()
    exact = [r for r in rows if r[0].variant.lower() == variant]
    if exact:
        return exact[0][0], exact[0][1]
    if not variant and rows:
        raise ProgramVariantRequired(key, [
            program_key(s.code, p.code, p.degree_type, p.variant) for p, s in rows])
    return None


def get_program(session: Session, key: str) -> ProgramInfo | None:
    found = find_program(session, key)
    return None if found is None else _programs_info(session, [found])[0]


def version_info(session: Session, version: ProgramVersion) -> ProgramVersionInfo:
    return _version_info(session, version)


__all__ = [
    "DiscoveredEntry",
    "InvalidProgramKey",
    "ProgramVariantRequired",
    "ProgramInfo",
    "ProgramVersionInfo",
    "SupportStatus",
    "find_program",
    "get_program",
    "list_discovered",
    "list_programs",
    "parse_program_key",
    "program_key",
    "support_status",
    "version_info",
]
