"""student audit cache

Revision ID: 9f217e335925
Revises: 0e8148bec496
Create Date: 2026-09-23 00:14:10.865367

WHY
---
Phase 5.6 measured a degree audit at ~50 ms of engine CPU per request, and
the engine is deterministic: identical inputs always give an identical
result. Recomputing it on every read is pure waste.

WHAT
----
One table, `student_audit_cache`, holding at most one cached audit per
student together with the fingerprints that say which inputs produced it.

This table is DERIVED STATE. Every row can be reconstructed by running the
Degree Engine again, and nothing academic is stored in queryable form - the
audit is an opaque serialized blob. It is never a source of academic truth.

Shape notes:

  * `student_id` is the PRIMARY KEY, so a student has at most one entry and
    a recomputation replaces it. Storage is bounded to O(students) with no
    reaper, and a superseded entry has nowhere to linger and be served.
  * `ON DELETE CASCADE`, the opposite of `student_link_event`'s RESTRICT,
    and deliberately so. A link event is evidence and must outlive things;
    a cached audit is a recomputable artifact that must not outlive its
    student, and derived state should never block a delete.
  * `result_json` is Text rather than JSON/JSONB. JSONB reorders keys and
    normalizes numerics, so a cached response would differ byte-for-byte
    from a freshly computed one - unacceptable when the entire claim is that
    a hit and a miss are indistinguishable to the client.

HOW EXISTING DATA BEHAVES
-------------------------
Additive only. No existing table is touched, nothing is backfilled, and no
academic row is read or written. The table starts empty and fills lazily on
the first audit per student; until then every request simply computes fresh,
which is exactly the Phase 5.6 behaviour.

The downgrade drops the table. That loses only cached bytes - no academic
record is affected, and the next request recomputes.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9f217e335925'
down_revision: str | None = '0e8148bec496'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_audit_cache',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('rules_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_audit_cache_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', name=op.f('pk_student_audit_cache'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_audit_cache')
    # ### end Alembic commands ###
