"""program registry lifecycle provenance and eligibility rules

Phase 6.3. Additive: three tables (catalog_page, program_candidate,
program_review), provenance/lifecycle columns on program_version, a variant
in the program natural key, and requirement.eligibility_rule. Existing rows
are preserved; the only data step maps existing versions into the
lifecycle (see upgrade). Downgrade restores the three-part natural key, which
fails if two variants of one program exist - by design, not silently.

Revision ID: 754dce693d0c
Revises: d839d664f019
Create Date: 2026-09-30 19:53:44.111617
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '754dce693d0c'
down_revision: str | None = 'd839d664f019'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_page',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('catalog_key', sa.String(length=32), nullable=False),
    sa.Column('catalog_year', sa.String(length=16), nullable=False),
    sa.Column('url_path', sa.Text(), nullable=False),
    sa.Column('source_page_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('school_slug', sa.String(length=64), nullable=False),
    sa.Column('trail', sa.Text(), nullable=False),
    sa.Column('page_class', sa.String(length=24), nullable=False),
    sa.Column('subject_code', sa.String(length=8), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('prose_sha256', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("page_class IN ('subject_coded','program_area','other','external')", name=op.f('ck_catalog_page_page_class_known')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['data_source.id'], name=op.f('fk_catalog_page_snapshot_id_data_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_page')),
    sa.UniqueConstraint('catalog_key', 'catalog_year', 'url_path', name='uq_catalog_page')
    )
    op.create_index(op.f('ix_catalog_page_source_page_id'), 'catalog_page', ['source_page_id'], unique=False)
    op.create_index('ix_catalog_page_year_school', 'catalog_page', ['catalog_year', 'school_slug'], unique=False)
    op.create_table('program_candidate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('catalog_page_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_key', sa.String(length=160), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('credential_type', sa.String(length=32), nullable=False),
    sa.Column('parent_candidate_key', sa.String(length=160), nullable=True),
    sa.Column('curriculum_code', sa.String(length=16), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('program_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("credential_type IN ('major','option','minor','certificate','interdisciplinary_major','unknown')", name=op.f('ck_program_candidate_credential_type_known')),
    sa.ForeignKeyConstraint(['catalog_page_id'], ['catalog_page.id'], name=op.f('fk_program_candidate_catalog_page_id_catalog_page'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_version_id'], ['program_version.id'], name=op.f('fk_program_candidate_program_version_id_program_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_candidate')),
    sa.UniqueConstraint('catalog_page_id', 'candidate_key', name='uq_program_candidate')
    )
    op.create_index(op.f('ix_program_candidate_catalog_page_id'), 'program_candidate', ['catalog_page_id'], unique=False)
    op.create_table('program_review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_version_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('source_prose_sha256', sa.String(length=64), nullable=False),
    sa.Column('definition_sha256', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('approved','changes_requested')", name=op.f('ck_program_review_review_decision_known')),
    sa.ForeignKeyConstraint(['program_version_id'], ['program_version.id'], name=op.f('fk_program_review_program_version_id_program_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_review'))
    )
    op.create_index(op.f('ix_program_review_program_version_id'), 'program_review', ['program_version_id'], unique=False)
    op.add_column('program', sa.Column('variant', sa.String(length=48), server_default='', nullable=False))
    op.drop_constraint(op.f('uq_program_natural_key'), 'program', type_='unique')
    op.create_unique_constraint('uq_program_natural_key', 'program', ['school_id', 'code', 'degree_type', 'variant'])
    op.add_column('program_version', sa.Column('lifecycle_state', sa.String(length=24), server_default='parsed', nullable=False))
    op.add_column('program_version', sa.Column('publication_basis', sa.String(length=24), nullable=True))
    op.add_column('program_version', sa.Column('catalog_page_id', sa.Uuid(), nullable=True))
    op.add_column('program_version', sa.Column('source_snapshot_id', sa.Uuid(), nullable=True))
    op.add_column('program_version', sa.Column('source_prose_sha256', sa.String(length=64), nullable=True))
    op.add_column('program_version', sa.Column('definition_sha256', sa.String(length=64), nullable=True))
    op.add_column('program_version', sa.Column('curated_by', sa.String(length=128), nullable=True))
    op.add_column('program_version', sa.Column('extractor_version', sa.String(length=64), nullable=True))
    op.add_column('program_version', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('program_version', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('program_version', sa.Column('admission_prose', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_program_version_source_snapshot_id_data_source'), 'program_version', 'data_source', ['source_snapshot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_program_version_catalog_page_id_catalog_page'), 'program_version', 'catalog_page', ['catalog_page_id'], ['id'], ondelete='SET NULL')
    op.add_column('requirement', sa.Column('eligibility_rule', sa.JSON(), nullable=True))
    # --- not detected by autogenerate: CHECKs on an existing table ---------
    op.create_check_constraint(
        op.f('ck_program_version_lifecycle_state_known'), 'program_version',
        "lifecycle_state IN ('parsed','validated','reviewed','published','needs_rereview')")
    op.create_check_constraint(
        op.f('ck_program_version_publication_basis_known'), 'program_version',
        "publication_basis IS NULL OR publication_basis IN ('human_review','legacy_curated')")

    # --- data: map existing versions into the lifecycle --------------------
    # A version the Phase 6.0 support rule already called SUPPORTED - every
    # node curated from prose, at least one requirement - is grandfathered as
    # published with basis 'legacy_curated'. No reviewer is invented: the
    # basis says exactly that it predates review records. Everything else
    # (Mathematics: 'unverified') stays 'parsed' and must earn its way up.
    op.execute("""
        UPDATE program_version v
           SET lifecycle_state = 'published', publication_basis = 'legacy_curated'
         WHERE v.curation_status = 'curated_from_prose'
           AND EXISTS (SELECT 1 FROM requirement r WHERE r.program_version_id = v.id)
           AND NOT EXISTS (SELECT 1 FROM requirement r WHERE r.program_version_id = v.id
                             AND r.curation_status <> 'curated_from_prose')
           AND NOT EXISTS (SELECT 1 FROM program_rule r WHERE r.program_version_id = v.id
                             AND r.curation_status <> 'curated_from_prose')
    """)
    op.create_check_constraint(
        op.f('ck_program_version_published_has_basis'), 'program_version',
        "lifecycle_state <> 'published' OR publication_basis IS NOT NULL")
    # The Mathematics B.A. loaded in Phase 6.0 IS Option A (its definition
    # says so); variant is now part of its identity. Renaming it in place
    # keeps its version, requirements and any student binding instead of
    # leaving a variant-less duplicate beside the reloaded definition.
    op.execute("""
        UPDATE program p SET variant = 'option-a'
          FROM school s
         WHERE s.id = p.school_id AND s.code = 'SAS'
           AND p.code = '640' AND p.degree_type = 'BA' AND p.variant = ''
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_program_version_published_has_basis'), 'program_version', type_='check')
    op.drop_constraint(op.f('ck_program_version_publication_basis_known'), 'program_version', type_='check')
    op.drop_constraint(op.f('ck_program_version_lifecycle_state_known'), 'program_version', type_='check')
    op.drop_column('requirement', 'eligibility_rule')
    op.drop_constraint(op.f('fk_program_version_catalog_page_id_catalog_page'), 'program_version', type_='foreignkey')
    op.drop_constraint(op.f('fk_program_version_source_snapshot_id_data_source'), 'program_version', type_='foreignkey')
    op.drop_column('program_version', 'admission_prose')
    op.drop_column('program_version', 'last_checked_at')
    op.drop_column('program_version', 'validated_at')
    op.drop_column('program_version', 'extractor_version')
    op.drop_column('program_version', 'curated_by')
    op.drop_column('program_version', 'definition_sha256')
    op.drop_column('program_version', 'source_prose_sha256')
    op.drop_column('program_version', 'source_snapshot_id')
    op.drop_column('program_version', 'catalog_page_id')
    op.drop_column('program_version', 'publication_basis')
    op.drop_column('program_version', 'lifecycle_state')
    # Fails by design if two variants of one program now exist: dropping the
    # variant would merge distinct curricula.
    op.drop_constraint('uq_program_natural_key', 'program', type_='unique')
    op.create_unique_constraint(op.f('uq_program_natural_key'), 'program', ['school_id', 'code', 'degree_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('program', 'variant')
    op.drop_index(op.f('ix_program_review_program_version_id'), table_name='program_review')
    op.drop_table('program_review')
    op.drop_index(op.f('ix_program_candidate_catalog_page_id'), table_name='program_candidate')
    op.drop_table('program_candidate')
    op.drop_index('ix_catalog_page_year_school', table_name='catalog_page')
    op.drop_index(op.f('ix_catalog_page_source_page_id'), table_name='catalog_page')
    op.drop_table('catalog_page')
    # ### end Alembic commands ###
