"""catalog and degree requirements

Revision ID: 437d81e0faef
Revises: ef89e1066a73
Create Date: 2026-09-13 01:21:50.748554
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '437d81e0faef'
down_revision: str | None = 'ef89e1066a73'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('campus_code', sa.String(length=16), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_school_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school')),
    sa.UniqueConstraint('code', name='uq_school_code')
    )
    op.create_table('program',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('degree_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('fk_program_school_id_school')),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_program_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program')),
    sa.UniqueConstraint('school_id', 'code', 'degree_type', name='uq_program_natural_key')
    )
    op.create_index(op.f('ix_program_school_id'), 'program', ['school_id'], unique=False)
    op.create_table('catalog_course_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_year', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits_min', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('credits_max', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('credits_raw', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits_max IS NULL OR credits_min IS NULL OR credits_max >= credits_min', name=op.f('ck_catalog_course_entry_catalog_credits_range_ordered')),
    sa.CheckConstraint('credits_min IS NULL OR credits_min >= 0', name=op.f('ck_catalog_course_entry_catalog_credits_min_non_negative')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_catalog_course_entry_course_id_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_catalog_course_entry_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_course_entry')),
    sa.UniqueConstraint('course_id', 'catalog_year', name='uq_catalog_entry_course_year')
    )
    op.create_index(op.f('ix_catalog_course_entry_catalog_year'), 'catalog_course_entry', ['catalog_year'], unique=False)
    op.create_index(op.f('ix_catalog_course_entry_course_id'), 'catalog_course_entry', ['course_id'], unique=False)
    op.create_table('program_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_year', sa.String(length=16), nullable=False),
    sa.Column('total_credits_min', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('total_credits_max', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('source_prose', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('curation_status', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_credits_max IS NULL OR total_credits_min IS NULL OR total_credits_max >= total_credits_min', name=op.f('ck_program_version_total_credits_range_ordered')),
    sa.CheckConstraint('total_credits_min IS NULL OR total_credits_min >= 0', name=op.f('ck_program_version_total_credits_min_non_negative')),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('fk_program_version_program_id_program'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_program_version_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_version')),
    sa.UniqueConstraint('program_id', 'catalog_year', name='uq_program_version')
    )
    op.create_index(op.f('ix_program_version_catalog_year'), 'program_version', ['catalog_year'], unique=False)
    op.create_index(op.f('ix_program_version_program_id'), 'program_version', ['program_id'], unique=False)
    op.create_table('requirement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_version_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('requirement_type', sa.String(length=24), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('min_count', sa.Integer(), nullable=True),
    sa.Column('min_credits', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('max_outside_subject', sa.Integer(), nullable=True),
    sa.Column('constraint_subject_code', sa.String(length=8), nullable=True),
    sa.Column('min_at_level', sa.Integer(), nullable=True),
    sa.Column('min_at_level_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_prose', sa.Text(), nullable=True),
    sa.Column('curation_status', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("requirement_type IN ('all_of','any_of','choose_n','credits','course')", name=op.f('ck_requirement_requirement_type_known')),
    sa.CheckConstraint('min_count IS NULL OR min_count >= 0', name=op.f('ck_requirement_min_count_non_negative')),
    sa.CheckConstraint('min_credits IS NULL OR min_credits >= 0', name=op.f('ck_requirement_min_credits_non_negative')),
    sa.ForeignKeyConstraint(['parent_id'], ['requirement.id'], name=op.f('fk_requirement_parent_id_requirement'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_version_id'], ['program_version.id'], name=op.f('fk_requirement_program_version_id_program_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_requirement_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement')),
    sa.UniqueConstraint('program_version_id', 'code', name='uq_requirement_code')
    )
    op.create_index(op.f('ix_requirement_parent_id'), 'requirement', ['parent_id'], unique=False)
    op.create_index('ix_requirement_parent_sort', 'requirement', ['parent_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_requirement_program_version_id'), 'requirement', ['program_version_id'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('catalog_year', sa.String(length=16), nullable=False),
    sa.Column('program_version_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_version_id'], ['program_version.id'], name=op.f('fk_student_program_version_id_program_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student')),
    sa.UniqueConstraint('external_ref', name='uq_student_external_ref')
    )
    op.create_index(op.f('ix_student_program_version_id'), 'student', ['program_version_id'], unique=False)
    op.create_table('requirement_course_option',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('credits_applied', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('min_grade', sa.String(length=4), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_requirement_course_option_course_id_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], name=op.f('fk_requirement_course_option_requirement_id_requirement'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_requirement_course_option_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_course_option')),
    sa.UniqueConstraint('requirement_id', 'course_id', name='uq_requirement_course')
    )
    op.create_index(op.f('ix_requirement_course_option_course_id'), 'requirement_course_option', ['course_id'], unique=False)
    op.create_index(op.f('ix_requirement_course_option_requirement_id'), 'requirement_course_option', ['requirement_id'], unique=False)
    op.create_table('student_course',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('term_code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('credits_earned', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'completed' OR grade IS NOT NULL", name=op.f('ck_student_course_completed_requires_grade')),
    sa.CheckConstraint("status IN ('completed','in_progress','planned')", name=op.f('ck_student_course_student_course_status_known')),
    sa.CheckConstraint('credits_earned IS NULL OR credits_earned >= 0', name=op.f('ck_student_course_credits_earned_non_negative')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_student_course_course_id_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_course_student_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_course')),
    sa.UniqueConstraint('student_id', 'course_id', 'term_code', name='uq_student_course_term')
    )
    op.create_index(op.f('ix_student_course_course_id'), 'student_course', ['course_id'], unique=False)
    op.create_index('ix_student_course_status', 'student_course', ['student_id', 'status'], unique=False)
    op.create_index(op.f('ix_student_course_student_id'), 'student_course', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_course_student_id'), table_name='student_course')
    op.drop_index('ix_student_course_status', table_name='student_course')
    op.drop_index(op.f('ix_student_course_course_id'), table_name='student_course')
    op.drop_table('student_course')
    op.drop_index(op.f('ix_requirement_course_option_requirement_id'), table_name='requirement_course_option')
    op.drop_index(op.f('ix_requirement_course_option_course_id'), table_name='requirement_course_option')
    op.drop_table('requirement_course_option')
    op.drop_index(op.f('ix_student_program_version_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_requirement_program_version_id'), table_name='requirement')
    op.drop_index('ix_requirement_parent_sort', table_name='requirement')
    op.drop_index(op.f('ix_requirement_parent_id'), table_name='requirement')
    op.drop_table('requirement')
    op.drop_index(op.f('ix_program_version_program_id'), table_name='program_version')
    op.drop_index(op.f('ix_program_version_catalog_year'), table_name='program_version')
    op.drop_table('program_version')
    op.drop_index(op.f('ix_catalog_course_entry_course_id'), table_name='catalog_course_entry')
    op.drop_index(op.f('ix_catalog_course_entry_catalog_year'), table_name='catalog_course_entry')
    op.drop_table('catalog_course_entry')
    op.drop_index(op.f('ix_program_school_id'), table_name='program')
    op.drop_table('program')
    op.drop_table('school')
    # ### end Alembic commands ###
