"""section session dates and structured restrictions

Phase 6.6 (Schedule Engine). Additive only:

  * course_section.session_dates_raw / session_start_date / session_end_date
    - SOC sessionDates, published on every Summer 2026 section and needed for
    date-aware conflict detection; plus a CHECK that start <= end;
  * section_restriction - SOC's structured "open to" lists (majors, minors,
    unitMajors, honorPrograms), previously kept only as openToText prose.

Existing rows keep their meaning (NULL dates = not published; no restriction
rows until sections are re-ingested from the archived SOC payloads, which is
idempotent). The downgrade drops only what this revision added.

Revision ID: 87bec76b788c
Revises: 6ba645ee0f9c
Create Date: 2026-10-05 01:24:56.318400
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '87bec76b788c'
down_revision: str | None = '6ba645ee0f9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_restriction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('unit_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('major','unit','minor','unit_major','honor_program')", name=op.f('ck_section_restriction_restriction_kind_known')),
    sa.CheckConstraint('length(trim(code)) > 0', name=op.f('ck_section_restriction_restriction_code_not_blank')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_section_restriction_restriction_ordinal_non_negative')),
    sa.ForeignKeyConstraint(['section_id'], ['course_section.id'], name=op.f('fk_section_restriction_section_id_course_section'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section_restriction')),
    sa.UniqueConstraint('section_id', 'ordinal', name='uq_restriction_section_ordinal')
    )
    op.create_index(op.f('ix_section_restriction_section_id'), 'section_restriction', ['section_id'], unique=False)
    op.add_column('course_section', sa.Column('session_dates_raw', sa.Text(), nullable=True))
    op.add_column('course_section', sa.Column('session_start_date', sa.Date(), nullable=True))
    op.add_column('course_section', sa.Column('session_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###

    op.create_check_constraint(
        op.f('ck_course_section_session_dates_ordered'), 'course_section',
        "session_start_date IS NULL OR session_end_date IS NULL "
        "OR session_start_date <= session_end_date")


def downgrade() -> None:
    op.drop_constraint(op.f('ck_course_section_session_dates_ordered'), 'course_section',
                       type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_section', 'session_end_date')
    op.drop_column('course_section', 'session_start_date')
    op.drop_column('course_section', 'session_dates_raw')
    op.drop_index(op.f('ix_section_restriction_section_id'), table_name='section_restriction')
    op.drop_table('section_restriction')
    # ### end Alembic commands ###
