"""requirement sharing policy

Revision ID: be0ed2042e56
Revises: 62b929a5bd2e
Create Date: 2026-09-14 16:27:52.168373
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'be0ed2042e56'
down_revision: str | None = '62b929a5bd2e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerated, then corrected by hand for two reasons:
    #
    #  1. A bare NOT NULL add_column fails on any populated table. Both of
    #     these tables have rows, so each column is added WITH a server_default
    #     which PostgreSQL uses to backfill existing rows in one pass.
    #
    #  2. Autogenerate did not emit the sharing_policy CHECK constraint, so it
    #     is added explicitly below. Without it an unknown policy value would
    #     make the allocator silently fall back to a default.
    #
    # The defaults are the SAFE values: every existing requirement becomes a
    # 'major' requirement, and every existing program stays 'exclusive', so
    # applying this migration cannot change any existing audit result.
    op.add_column(
        'program_version',
        sa.Column(
            'sharing_policy',
            sa.String(length=32),
            nullable=False,
            server_default='exclusive',
        ),
    )
    op.add_column(
        'requirement',
        sa.Column(
            'requirement_system',
            sa.String(length=32),
            nullable=False,
            server_default='major',
        ),
    )
    op.create_index(
        op.f('ix_requirement_requirement_system'),
        'requirement',
        ['requirement_system'],
        unique=False,
    )
    # Pass the BARE name: the metadata naming convention
    # ("ck_%(table_name)s_%(constraint_name)s") adds the prefix. Passing an
    # already-prefixed name yields a doubled one that will not match the model
    # definition, and a later autogenerate would try to drop and recreate it.
    op.create_check_constraint(
        'sharing_policy_known',
        'program_version',
        "sharing_policy IN ('exclusive','share_across_systems')",
    )

    # The server_defaults existed only to backfill. Dropping them keeps the
    # application's defaults (in the ORM) the single source of truth, so a row
    # inserted without a value fails loudly rather than picking up a silent
    # database-side value.
    op.alter_column('program_version', 'sharing_policy', server_default=None)
    op.alter_column('requirement', 'requirement_system', server_default=None)


def downgrade() -> None:
    op.drop_constraint('sharing_policy_known', 'program_version', type_='check')
    op.drop_index(op.f('ix_requirement_requirement_system'), table_name='requirement')
    op.drop_column('requirement', 'requirement_system')
    op.drop_column('program_version', 'sharing_policy')
