"""section ingestion schema

Revision ID: ef89e1066a73
Revises: 27348b5d362d
Create Date: 2026-09-09 16:22:47.922538
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ef89e1066a73'
down_revision: str | None = '27348b5d362d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_section',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('term_code', sa.String(length=16), nullable=False),
    sa.Column('index_number', sa.String(length=16), nullable=False),
    sa.Column('section_number', sa.String(length=16), nullable=False),
    sa.Column('campus_code', sa.String(length=16), nullable=False),
    sa.Column('open_status', sa.Boolean(), nullable=False),
    sa.Column('open_status_text', sa.String(length=32), nullable=True),
    sa.Column('section_course_type', sa.String(length=8), nullable=True),
    sa.Column('exam_code', sa.String(length=8), nullable=True),
    sa.Column('exam_code_text', sa.Text(), nullable=True),
    sa.Column('final_exam', sa.Text(), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('section_notes', sa.Text(), nullable=True),
    sa.Column('comments_text', sa.Text(), nullable=True),
    sa.Column('open_to_text', sa.Text(), nullable=True),
    sa.Column('section_eligibility', sa.Text(), nullable=True),
    sa.Column('special_permission_add_code', sa.String(length=8), nullable=True),
    sa.Column('special_permission_add_description', sa.Text(), nullable=True),
    sa.Column('special_permission_drop_code', sa.String(length=8), nullable=True),
    sa.Column('special_permission_drop_description', sa.Text(), nullable=True),
    sa.Column('cross_listed_section_type', sa.String(length=8), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("index_number ~ '^[0-9]+$'", name=op.f('ck_course_section_index_number_numeric')),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offering.id'], name=op.f('fk_course_section_offering_id_course_offering'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_course_section_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_section')),
    sa.UniqueConstraint('offering_id', 'section_number', name='uq_section_offering_number'),
    sa.UniqueConstraint('term_code', 'index_number', name='uq_section_term_index')
    )
    op.create_index(op.f('ix_course_section_index_number'), 'course_section', ['index_number'], unique=False)
    op.create_index(op.f('ix_course_section_offering_id'), 'course_section', ['offering_id'], unique=False)
    op.create_index(op.f('ix_course_section_term_code'), 'course_section', ['term_code'], unique=False)
    op.create_index('ix_section_offering_open', 'course_section', ['offering_id', 'open_status'], unique=False)
    op.create_table('section_cross_listing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('registration_index', sa.String(length=16), nullable=False),
    sa.Column('primary_registration_index', sa.String(length=16), nullable=True),
    sa.Column('offering_unit_code', sa.String(length=8), nullable=True),
    sa.Column('subject_code', sa.String(length=8), nullable=True),
    sa.Column('course_number', sa.String(length=16), nullable=True),
    sa.Column('supplement_code', sa.String(length=8), nullable=False),
    sa.Column('section_number', sa.String(length=16), nullable=True),
    sa.Column('offering_unit_campus', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['course_section.id'], name=op.f('fk_section_cross_listing_section_id_course_section'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section_cross_listing')),
    sa.UniqueConstraint('section_id', 'registration_index', name='uq_xlist_section_index')
    )
    op.create_index(op.f('ix_section_cross_listing_registration_index'), 'section_cross_listing', ['registration_index'], unique=False)
    op.create_index(op.f('ix_section_cross_listing_section_id'), 'section_cross_listing', ['section_id'], unique=False)
    op.create_table('section_instructor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('instructor_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('instructor_index >= 0', name=op.f('ck_section_instructor_instructor_index_non_negative')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_section_instructor_instructor_name_not_blank')),
    sa.ForeignKeyConstraint(['section_id'], ['course_section.id'], name=op.f('fk_section_instructor_section_id_course_section'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section_instructor')),
    sa.UniqueConstraint('section_id', 'instructor_index', name='uq_instructor_section_index')
    )
    op.create_index(op.f('ix_section_instructor_name'), 'section_instructor', ['name'], unique=False)
    op.create_index(op.f('ix_section_instructor_section_id'), 'section_instructor', ['section_id'], unique=False)
    op.create_table('section_meeting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('meeting_index', sa.Integer(), nullable=False),
    sa.Column('meeting_day', sa.String(length=1), nullable=True),
    sa.Column('start_time_military', sa.String(length=4), nullable=True),
    sa.Column('end_time_military', sa.String(length=4), nullable=True),
    sa.Column('meeting_mode_code', sa.String(length=8), nullable=False),
    sa.Column('meeting_mode_desc', sa.String(length=64), nullable=True),
    sa.Column('building_code', sa.String(length=16), nullable=True),
    sa.Column('room_number', sa.String(length=32), nullable=True),
    sa.Column('campus_location', sa.String(length=16), nullable=True),
    sa.Column('campus_name', sa.String(length=64), nullable=True),
    sa.Column('campus_abbrev', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("end_time_military IS NULL OR end_time_military ~ '^[0-9]{4}$'", name=op.f('ck_section_meeting_end_time_format')),
    sa.CheckConstraint("meeting_day IS NULL OR meeting_day IN ('M','T','W','H','F','S','U')", name=op.f('ck_section_meeting_meeting_day_valid')),
    sa.CheckConstraint("start_time_military IS NULL OR start_time_military ~ '^[0-9]{4}$'", name=op.f('ck_section_meeting_start_time_format')),
    sa.CheckConstraint('(start_time_military IS NULL) = (end_time_military IS NULL)', name=op.f('ck_section_meeting_times_paired')),
    sa.CheckConstraint('meeting_index >= 0', name=op.f('ck_section_meeting_meeting_index_non_negative')),
    sa.ForeignKeyConstraint(['section_id'], ['course_section.id'], name=op.f('fk_section_meeting_section_id_course_section'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section_meeting')),
    sa.UniqueConstraint('section_id', 'meeting_index', name='uq_meeting_section_index')
    )
    op.create_index('ix_meeting_day_time', 'section_meeting', ['meeting_day', 'start_time_military'], unique=False)
    op.create_index(op.f('ix_section_meeting_section_id'), 'section_meeting', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_section_meeting_section_id'), table_name='section_meeting')
    op.drop_index('ix_meeting_day_time', table_name='section_meeting')
    op.drop_table('section_meeting')
    op.drop_index(op.f('ix_section_instructor_section_id'), table_name='section_instructor')
    op.drop_index(op.f('ix_section_instructor_name'), table_name='section_instructor')
    op.drop_table('section_instructor')
    op.drop_index(op.f('ix_section_cross_listing_section_id'), table_name='section_cross_listing')
    op.drop_index(op.f('ix_section_cross_listing_registration_index'), table_name='section_cross_listing')
    op.drop_table('section_cross_listing')
    op.drop_index('ix_section_offering_open', table_name='course_section')
    op.drop_index(op.f('ix_course_section_term_code'), table_name='course_section')
    op.drop_index(op.f('ix_course_section_offering_id'), table_name='course_section')
    op.drop_index(op.f('ix_course_section_index_number'), table_name='course_section')
    op.drop_table('course_section')
    # ### end Alembic commands ###
