"""student link audit trail and admin flag

Revision ID: 0e8148bec496
Revises: d35eb3a64b5d
Create Date: 2026-09-22 12:25:27.688270

Phase 5.5. Reviewed after autogeneration.

WHY THE SCHEMA MUST CHANGE
    Linking changes who may reach a person's transcript. That needs (a) a
    way to say which accounts may perform it, and (b) a record of every
    change. Neither can live in application code: an admin flag that is not
    in the database can be granted by a request, and a trail held in logs
    can be rotated away.

WHAT THIS CHANGES
    * user_account.is_admin - BOOLEAN NOT NULL DEFAULT false. Server-only;
      no request field and no token claim can set it.
    * student_link_event - append-only audit trail with FKs to the student,
      the affected account and the acting admin, all ondelete=RESTRICT so
      history cannot be erased by deleting a row it refers to. A CHECK pins
      the action vocabulary.

HOW EXISTING DATA BEHAVES
    is_admin arrives with server_default 'false', so every existing account
    becomes a NORMAL user. No account is silently granted administrative
    authority by a migration - the first admin must be created deliberately
    by someone with direct database access, which is the correct trust root.

    No student ownership is created, changed or removed here. The one
    existing student row stays exactly as it is, unlinked.

    student_link_event starts empty. It is NOT backfilled with a synthetic
    "linked" event for pre-existing ownership, because no such event
    happened and inventing history in an audit trail defeats its purpose.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0e8148bec496'
down_revision: str | None = 'd35eb3a64b5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_link_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('user_account_id', sa.Uuid(), nullable=False),
    sa.Column('performed_by_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('linked','unlinked')", name=op.f('ck_student_link_event_action_known')),
    sa.ForeignKeyConstraint(['performed_by_id'], ['user_account.id'], name=op.f('fk_student_link_event_performed_by_id_user_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_link_event_student_id_student'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], name=op.f('fk_student_link_event_user_account_id_user_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_link_event'))
    )
    op.create_index(op.f('ix_student_link_event_performed_by_id'), 'student_link_event', ['performed_by_id'], unique=False)
    op.create_index(op.f('ix_student_link_event_student_id'), 'student_link_event', ['student_id'], unique=False)
    op.create_index('ix_student_link_event_student_time', 'student_link_event', ['student_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_student_link_event_user_account_id'), 'student_link_event', ['user_account_id'], unique=False)
    op.add_column('user_account', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'is_admin')
    op.drop_index(op.f('ix_student_link_event_user_account_id'), table_name='student_link_event')
    op.drop_index('ix_student_link_event_student_time', table_name='student_link_event')
    op.drop_index(op.f('ix_student_link_event_student_id'), table_name='student_link_event')
    op.drop_index(op.f('ix_student_link_event_performed_by_id'), table_name='student_link_event')
    op.drop_table('student_link_event')
    # ### end Alembic commands ###
