"""user accounts and student ownership

Revision ID: d35eb3a64b5d
Revises: d0821611331c
Create Date: 2026-09-22 11:54:51.096014

Phase 5.4. Reviewed after autogeneration; the reasoning below is the part
that matters.

WHY THE SCHEMA MUST CHANGE
    Phase 5.3 derived the student from the credential instead of the request
    body, which stopped one caller naming another. But nothing verified the
    credential, and `Student` had no owner - so "whose record is this?" had
    no answer in the data. An application-level check cannot supply one, and
    cannot survive a race between two concurrent first-logins.

WHY AN EXISTING TABLE CANNOT EXPRESS IT
    `student.external_ref` is a label: nullable, client-visible, and set by
    the ingestion/test path. Anyone could type one. Ownership has to be a
    foreign key the server alone can write.

WHAT THIS CHANGES
    * creates `user_account` with UNIQUE(identity_provider, external_subject)
      - the final authority against duplicate accounts for one subject;
    * adds `student.user_id`, NULLABLE, UNIQUE, FK ondelete=RESTRICT.

HOW EXISTING DATA BEHAVES
    `user_id` is NULLABLE and there is deliberately NO BACKFILL. The dev
    database holds one student row with an `external_ref`, and that string is
    not evidence of who owns the record. Silently assigning it an identity
    would be inventing an ownership claim, so existing rows stay unlinked and
    the API reports that state explicitly (409, see DATA_MODEL.md 26.6).

    NOT NULL is deliberately not enforced yet: it would be a lie about data
    that legitimately predates accounts, and it can be tightened later once
    every live student has been linked.

    ondelete=RESTRICT, never CASCADE: deleting an account must not delete an
    academic record.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd35eb3a64b5d'
down_revision: str | None = 'd0821611331c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identity_provider', sa.String(length=32), nullable=False),
    sa.Column('external_subject', sa.String(length=255), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('identity_provider', 'external_subject', name='uq_user_account_identity')
    )
    op.create_index('ix_user_account_identity', 'user_account', ['identity_provider', 'external_subject'], unique=False)
    op.add_column('student', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_student_user_id'), 'student', ['user_id'], unique=True)
    op.create_foreign_key(op.f('fk_student_user_id_user_account'), 'student', 'user_account', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_student_user_id_user_account'), 'student', type_='foreignkey')
    op.drop_index(op.f('ix_student_user_id'), table_name='student')
    op.drop_column('student', 'user_id')
    op.drop_index('ix_user_account_identity', table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
