"""term-scoped course prerequisites and source coverage

Phase 6.2. Additive only: two new tables and two nullable columns. No
existing row is rewritten, so upgrading preserves all data; the data_source
CHECK allows NULL, which every existing row has.

Revision ID: d839d664f019
Revises: ce2b9afd3fa7
Create Date: 2026-09-29 15:58:46.708229
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd839d664f019'
down_revision: str | None = 'ce2b9afd3fa7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_prerequisite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('term_code', sa.String(length=16), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_text_sha256', sa.String(length=64), nullable=True),
    sa.Column('condition_note', sa.Text(), nullable=True),
    sa.Column('condition_kinds', sa.String(length=128), nullable=True),
    sa.Column('classification', sa.String(length=40), nullable=False),
    sa.Column('expression', sa.JSON(), nullable=True),
    sa.Column('canonical_text', sa.Text(), nullable=True),
    sa.Column('parse_detail', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification IN ('parsed','unsupported_minimum_course_level','unsupported_ambiguous_precedence','malformed','unknown','condition_note_only')", name=op.f('ck_course_prerequisite_classification_known')),
    sa.CheckConstraint('raw_text IS NOT NULL OR condition_note IS NOT NULL', name=op.f('ck_course_prerequisite_has_source_text')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_course_prerequisite_course_id_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offering.id'], name=op.f('fk_course_prerequisite_offering_id_course_offering'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_course_prerequisite_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_prerequisite')),
    sa.UniqueConstraint('offering_id', name=op.f('uq_course_prerequisite_offering_id'))
    )
    op.create_index('ix_course_prerequisite_course_term', 'course_prerequisite', ['course_id', 'term_code'], unique=False)
    op.create_table('prerequisite_reference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prerequisite_id', sa.Uuid(), nullable=False),
    sa.Column('course_string', sa.String(length=32), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_prerequisite_reference_course_id_course'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['course_prerequisite.id'], name=op.f('fk_prerequisite_reference_prerequisite_id_course_prerequisite'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prerequisite_reference')),
    sa.UniqueConstraint('prerequisite_id', 'course_string', name='uq_prerequisite_reference')
    )
    op.create_index(op.f('ix_prerequisite_reference_course_id'), 'prerequisite_reference', ['course_id'], unique=False)
    op.create_index(op.f('ix_prerequisite_reference_course_string'), 'prerequisite_reference', ['course_string'], unique=False)
    op.add_column('data_source', sa.Column('coverage', sa.String(length=16), nullable=True))
    op.add_column('data_source', sa.Column('coverage_note', sa.Text(), nullable=True))
    # Not detected by autogenerate (CHECK on an existing table).
    op.create_check_constraint(
        op.f('ck_data_source_coverage_known'), 'data_source',
        "coverage IS NULL OR coverage IN ('complete','partial','unknown')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_data_source_coverage_known'), 'data_source', type_='check')
    op.drop_column('data_source', 'coverage_note')
    op.drop_column('data_source', 'coverage')
    op.drop_index(op.f('ix_prerequisite_reference_course_string'), table_name='prerequisite_reference')
    op.drop_index(op.f('ix_prerequisite_reference_course_id'), table_name='prerequisite_reference')
    op.drop_table('prerequisite_reference')
    op.drop_index('ix_course_prerequisite_course_term', table_name='course_prerequisite')
    op.drop_table('course_prerequisite')
    # ### end Alembic commands ###
