"""initial course ingestion schema

Revision ID: 27348b5d362d
Revises: 
Create Date: 2026-09-08 16:19:56.177439
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '27348b5d362d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerated, then reviewed by hand:
    #  * server_default switched from the SQLite-flavored '(CURRENT_TIMESTAMP)'
    #    emitted by autogenerate to sa.func.now(), which renders correctly on
    #    both Postgres and SQLite.
    op.create_table('data_source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload_ref', sa.Text(), nullable=True),
    sa.Column('academic_year', sa.String(length=16), nullable=True),
    sa.Column('term_code', sa.String(length=16), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source'))
    )
    op.create_index(op.f('ix_data_source_content_hash'), 'data_source', ['content_hash'], unique=False)
    op.create_index('ix_data_source_kind_term', 'data_source', ['kind', 'term_code'], unique=False)
    op.create_index(op.f('ix_data_source_term_code'), 'data_source', ['term_code'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('offering_unit_code', sa.String(length=8), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_subject_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject')),
    sa.UniqueConstraint('offering_unit_code', 'code', name='uq_subject_unit_code')
    )
    op.create_index(op.f('ix_subject_code'), 'subject', ['code'], unique=False)
    op.create_table('course',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offering_unit_code', sa.String(length=8), nullable=False),
    sa.Column('subject_code', sa.String(length=8), nullable=False),
    sa.Column('course_number', sa.String(length=16), nullable=False),
    sa.Column('supplement_code', sa.String(length=8), nullable=False),
    sa.Column('course_string', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_abbrev', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('credits_description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=4), nullable=True),
    sa.Column('school_code', sa.String(length=8), nullable=True),
    sa.Column('school_description', sa.Text(), nullable=True),
    sa.Column('prereq_notes_raw', sa.Text(), nullable=True),
    sa.Column('synopsis_url', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('credits IS NULL OR credits >= 0', name=op.f('ck_course_credits_non_negative')),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_course_source_id_data_source')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_course_subject_id_subject')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course')),
    sa.UniqueConstraint('offering_unit_code', 'subject_code', 'course_number', 'supplement_code', name='uq_course_natural_key')
    )
    op.create_index(op.f('ix_course_course_string'), 'course', ['course_string'], unique=False)
    op.create_index(op.f('ix_course_level'), 'course', ['level'], unique=False)
    op.create_index(op.f('ix_course_subject_id'), 'course', ['subject_id'], unique=False)
    op.create_index('ix_course_subject_number', 'course', ['subject_code', 'course_number'], unique=False)
    op.create_table('course_offering',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('term_code', sa.String(length=16), nullable=False),
    sa.Column('campus_code', sa.String(length=16), nullable=False),
    sa.Column('open_sections_observed', sa.Integer(), nullable=True),
    sa.Column('section_count_observed', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_course_offering_course_id_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_course_offering_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_offering')),
    sa.UniqueConstraint('course_id', 'term_code', 'campus_code', name='uq_offering_course_term_campus')
    )
    op.create_index(op.f('ix_course_offering_course_id'), 'course_offering', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_offering_term_code'), 'course_offering', ['term_code'], unique=False)


def downgrade() -> None:
    # Tables are dropped in reverse dependency order so foreign keys never
    # reference a table that has already gone.
    op.drop_index(op.f('ix_course_offering_term_code'), table_name='course_offering')
    op.drop_index(op.f('ix_course_offering_course_id'), table_name='course_offering')
    op.drop_table('course_offering')
    op.drop_index('ix_course_subject_number', table_name='course')
    op.drop_index(op.f('ix_course_subject_id'), table_name='course')
    op.drop_index(op.f('ix_course_level'), table_name='course')
    op.drop_index(op.f('ix_course_course_string'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_subject_code'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_data_source_term_code'), table_name='data_source')
    op.drop_index('ix_data_source_kind_term', table_name='data_source')
    op.drop_index(op.f('ix_data_source_content_hash'), table_name='data_source')
    op.drop_table('data_source')
