"""distinct category eligibility

Revision ID: d0821611331c
Revises: be0ed2042e56
Create Date: 2026-09-20 15:30:49.250191
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd0821611331c'
down_revision: str | None = 'be0ed2042e56'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerated, then reviewed. Two notes:
    #
    #  1. `category` is added WITH server_default='' so PostgreSQL backfills
    #     the existing rows in one pass. Every pre-existing option becomes
    #     category='' (a major requirement has no sub-category), so the new
    #     unique constraint is equivalent to the old one for them and no
    #     existing audit changes.
    #
    #  2. Autogenerate did NOT emit the CHECK constraint - as with every
    #     previous migration in this project - so it is added explicitly.
    op.add_column(
        'requirement', sa.Column('min_distinct_categories', sa.Integer(), nullable=True)
    )
    op.add_column(
        'requirement_course_option',
        sa.Column('category', sa.String(length=16), server_default='', nullable=False),
    )
    op.drop_constraint(op.f('uq_requirement_course'), 'requirement_course_option', type_='unique')
    op.create_unique_constraint(
        'uq_requirement_course',
        'requirement_course_option',
        ['requirement_id', 'course_id', 'category'],
    )
    # Bare name: the metadata naming convention adds the ck_<table>_ prefix.
    op.create_check_constraint(
        'min_distinct_categories_non_negative',
        'requirement',
        'min_distinct_categories IS NULL OR min_distinct_categories >= 0',
    )

    # The server_default is KEPT, and the model declares it too. Dropping it
    # here was the first attempt and `alembic check` caught the divergence:
    # the database would have had no default while the mapping said it did.
    # Keeping it also means a row inserted outside the ORM gets '' rather
    # than failing the NOT NULL.


def downgrade() -> None:
    # op.f() marks the name as FINAL. Without it the naming convention adds a
    # second ck_requirement_ prefix - the same doubling bug as Phase 3.75.
    op.drop_constraint(
        op.f('ck_requirement_min_distinct_categories_non_negative'),
        'requirement',
        type_='check',
    )
    op.drop_constraint(op.f('uq_requirement_course'), 'requirement_course_option', type_='unique')
    # Collapsing back to (requirement, course) would violate uniqueness wherever
    # a course is certified under several categories, so those extra rows are
    # removed first - keeping the alphabetically first category per pair.
    op.execute(
        """
        DELETE FROM requirement_course_option a
        USING requirement_course_option b
        WHERE a.requirement_id = b.requirement_id
          AND a.course_id = b.course_id
          AND a.category > b.category
        """
    )
    op.create_unique_constraint(
        'uq_requirement_course', 'requirement_course_option', ['requirement_id', 'course_id']
    )
    op.drop_column('requirement_course_option', 'category')
    op.drop_column('requirement', 'min_distinct_categories')
