"""program rules and unlinked catalog entries

Revision ID: 62b929a5bd2e
Revises: 437d81e0faef
Create Date: 2026-09-13 18:55:25.802239
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '62b929a5bd2e'
down_revision: str | None = '437d81e0faef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_version_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('min_count', sa.Integer(), nullable=True),
    sa.Column('subject_code', sa.String(length=8), nullable=True),
    sa.Column('offering_unit_code', sa.String(length=8), nullable=True),
    sa.Column('excluded_course_strings', sa.Text(), nullable=True),
    sa.Column('is_evaluable', sa.Boolean(), nullable=False),
    sa.Column('not_evaluable_reason', sa.Text(), nullable=True),
    sa.Column('source_prose', sa.Text(), nullable=True),
    sa.Column('curation_status', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rule_type IN ('max_grade_count','course_exclusion','residency')", name=op.f('ck_program_rule_program_rule_type_known')),
    sa.CheckConstraint('is_evaluable OR not_evaluable_reason IS NOT NULL', name=op.f('ck_program_rule_not_evaluable_requires_reason')),
    sa.CheckConstraint('max_count IS NULL OR max_count >= 0', name=op.f('ck_program_rule_rule_max_count_non_negative')),
    sa.CheckConstraint('min_count IS NULL OR min_count >= 0', name=op.f('ck_program_rule_rule_min_count_non_negative')),
    sa.ForeignKeyConstraint(['program_version_id'], ['program_version.id'], name=op.f('fk_program_rule_program_version_id_program_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_program_rule_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_rule')),
    sa.UniqueConstraint('program_version_id', 'code', name='uq_program_rule_code')
    )
    op.create_index(op.f('ix_program_rule_program_version_id'), 'program_rule', ['program_version_id'], unique=False)
    # Three steps, not one: autogenerate emitted a NOT NULL add_column, which
    # fails on any table that already has rows. Add nullable, backfill from the
    # linked course, then enforce NOT NULL.
    op.add_column(
        'catalog_course_entry', sa.Column('course_string', sa.String(length=32), nullable=True)
    )
    op.execute(
        """
        UPDATE catalog_course_entry AS e
        SET course_string = c.course_string
        FROM course AS c
        WHERE c.id = e.course_id AND e.course_string IS NULL
        """
    )
    # Any row we cannot backfill has no course to derive a code from, and an
    # invented code would be worse than losing an unlinked row.
    op.execute("DELETE FROM catalog_course_entry WHERE course_string IS NULL")
    op.alter_column('catalog_course_entry', 'course_string', nullable=False)
    op.alter_column('catalog_course_entry', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_catalog_entry_course_year'), 'catalog_course_entry', type_='unique')
    op.create_unique_constraint('uq_catalog_entry_course_year', 'catalog_course_entry', ['course_string', 'catalog_year'])
    op.create_index(op.f('ix_catalog_course_entry_course_string'), 'catalog_course_entry', ['course_string'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_course_entry_course_string'), table_name='catalog_course_entry')
    op.drop_constraint('uq_catalog_entry_course_year', 'catalog_course_entry', type_='unique')
    op.create_unique_constraint(op.f('uq_catalog_entry_course_year'), 'catalog_course_entry', ['course_id', 'catalog_year'], postgresql_nulls_not_distinct=False)
    op.alter_column('catalog_course_entry', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('catalog_course_entry', 'course_string')
    op.drop_index(op.f('ix_program_rule_program_version_id'), table_name='program_rule')
    op.drop_table('program_rule')
    # ### end Alembic commands ###
