"""academic rule semantics: grades, quotas, sequences, gpa, credit origin, corequisites

Phase 6.4. Additive: every new column is nullable or defaulted, so existing
rows keep their meaning (credit_origin 'rutgers', no minimum grades, no
quotas). Three CHECK constraints are WIDENED, never narrowed:

  * student_course.completed_requires_grade - transfer/exam credit carries no
    Rutgers grade;
  * program_rule.program_rule_type_known - adds 'min_gpa';
  * course_prerequisite.has_source_text - a uniform section note is a source.

The downgrade refuses (rather than deletes) when rows exist that the narrower
constraints would reject: dropping them silently would lose academic data.

Revision ID: 6ba645ee0f9c
Revises: 754dce693d0c
Create Date: 2026-10-01 02:00:47.424227
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6ba645ee0f9c'
down_revision: str | None = '754dce693d0c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_corequisite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('term_code', sa.String(length=16), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_field', sa.String(length=24), nullable=False),
    sa.Column('classification', sa.String(length=24), nullable=False),
    sa.Column('expression', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('canonical_text', sa.Text(), nullable=True),
    sa.Column('parse_detail', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification IN ('parsed','unsupported')", name=op.f('ck_course_corequisite_corequisite_classification_known')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_course_corequisite_course_id_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offering.id'], name=op.f('fk_course_corequisite_offering_id_course_offering'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_course_corequisite_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_corequisite')),
    sa.UniqueConstraint('offering_id', name=op.f('uq_course_corequisite_offering_id'))
    )
    op.create_index('ix_course_corequisite_course_term', 'course_corequisite', ['course_id', 'term_code'], unique=False)
    op.add_column('course_prerequisite', sa.Column('section_condition_note', sa.Text(), nullable=True))
    op.add_column('course_prerequisite', sa.Column('interpreted_conditions', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('course_prerequisite', sa.Column('condition_parser_version', sa.String(length=16), nullable=True))
    op.add_column('program_rule', sa.Column('min_gpa', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('program_rule', sa.Column('gpa_scope', sa.String(length=32), nullable=True))
    op.add_column('requirement', sa.Column('min_grade', sa.String(length=4), nullable=True))
    op.add_column('requirement', sa.Column('grade_quota_max_count', sa.Integer(), nullable=True))
    op.add_column('requirement', sa.Column('grade_quota_at_most', sa.String(length=4), nullable=True))
    op.add_column('requirement', sa.Column('category_sequences', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('student_course', sa.Column('credit_origin', sa.String(length=16), server_default='rutgers', nullable=False))
    # ### end Alembic commands ###

    op.create_check_constraint(
        op.f('ck_student_course_credit_origin_known'), 'student_course',
        "credit_origin IN ('rutgers','transfer','exam_credit')")
    op.drop_constraint(op.f('ck_student_course_completed_requires_grade'), 'student_course', type_='check')
    op.create_check_constraint(
        op.f('ck_student_course_completed_requires_grade'), 'student_course',
        "status <> 'completed' OR grade IS NOT NULL OR credit_origin <> 'rutgers'")
    op.drop_constraint(op.f('ck_program_rule_program_rule_type_known'), 'program_rule', type_='check')
    op.create_check_constraint(
        op.f('ck_program_rule_program_rule_type_known'), 'program_rule',
        "rule_type IN ('max_grade_count','course_exclusion','residency','min_gpa')")
    op.drop_constraint(op.f('ck_course_prerequisite_has_source_text'), 'course_prerequisite', type_='check')
    op.create_check_constraint(
        op.f('ck_course_prerequisite_has_source_text'), 'course_prerequisite',
        "raw_text IS NOT NULL OR condition_note IS NOT NULL OR section_condition_note IS NOT NULL")
    op.create_check_constraint(
        op.f('ck_requirement_grade_quota_complete'), 'requirement',
        "grade_quota_max_count IS NULL OR "
        "(grade_quota_max_count >= 0 AND grade_quota_at_most IS NOT NULL)")


def _refuse_if(sql: str, what: str) -> None:
    count = op.get_bind().execute(sa.text(sql)).scalar()
    if count:
        raise RuntimeError(f"downgrade refused: {count} {what}; the pre-6.4 schema cannot hold "
                           "them and dropping them would lose academic data")


def downgrade() -> None:
    _refuse_if("SELECT count(*) FROM student_course WHERE status = 'completed' AND grade IS NULL",
               "completed transfer/exam-credit record(s) without a grade")
    _refuse_if("SELECT count(*) FROM program_rule WHERE rule_type = 'min_gpa'", "min_gpa rule(s)")
    _refuse_if("SELECT count(*) FROM course_prerequisite WHERE raw_text IS NULL "
               "AND condition_note IS NULL", "prerequisite row(s) sourced only from section notes")
    op.drop_constraint(op.f('ck_requirement_grade_quota_complete'), 'requirement', type_='check')
    op.drop_constraint(op.f('ck_course_prerequisite_has_source_text'), 'course_prerequisite', type_='check')
    op.create_check_constraint(
        op.f('ck_course_prerequisite_has_source_text'), 'course_prerequisite',
        "raw_text IS NOT NULL OR condition_note IS NOT NULL")
    op.drop_constraint(op.f('ck_program_rule_program_rule_type_known'), 'program_rule', type_='check')
    op.create_check_constraint(
        op.f('ck_program_rule_program_rule_type_known'), 'program_rule',
        "rule_type IN ('max_grade_count','course_exclusion','residency')")
    op.drop_constraint(op.f('ck_student_course_completed_requires_grade'), 'student_course', type_='check')
    op.create_check_constraint(
        op.f('ck_student_course_completed_requires_grade'), 'student_course',
        "status <> 'completed' OR grade IS NOT NULL")
    op.drop_constraint(op.f('ck_student_course_credit_origin_known'), 'student_course', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_course', 'credit_origin')
    op.drop_column('requirement', 'category_sequences')
    op.drop_column('requirement', 'grade_quota_at_most')
    op.drop_column('requirement', 'grade_quota_max_count')
    op.drop_column('requirement', 'min_grade')
    op.drop_column('program_rule', 'gpa_scope')
    op.drop_column('program_rule', 'min_gpa')
    op.drop_column('course_prerequisite', 'condition_parser_version')
    op.drop_column('course_prerequisite', 'interpreted_conditions')
    op.drop_column('course_prerequisite', 'section_condition_note')
    op.drop_index('ix_course_corequisite_course_term', table_name='course_corequisite')
    op.drop_table('course_corequisite')
    # ### end Alembic commands ###
